# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_float_scale.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_form(object):
    def setupUi(self, form):
        form.setObjectName("form")
        form.resize(320, 60)
        form.setMinimumSize(QtCore.QSize(320, 60))
        form.setMaximumSize(QtCore.QSize(320, 60))
        form.setWindowTitle("不透明度与缩放")
        self.formLayout = QtWidgets.QFormLayout(form)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(form)
        self.label.setText("滑动滑块调节页面缩放")
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label)
        self.horizontal_layout_scale = QtWidgets.QHBoxLayout()
        self.horizontal_layout_scale.setObjectName("horizontal_layout_scale")
        self.label_scale = QtWidgets.QLabel(form)
        self.label_scale.setText("缩放")
        self.label_scale.setObjectName("label_scale")
        self.horizontal_layout_scale.addWidget(self.label_scale)
        self.horizontal_slider_scale = QtWidgets.QSlider(form)
        self.horizontal_slider_scale.setMinimum(25)
        self.horizontal_slider_scale.setMaximum(500)
        self.horizontal_slider_scale.setSingleStep(5)
        self.horizontal_slider_scale.setProperty("value", 100)
        self.horizontal_slider_scale.setOrientation(QtCore.Qt.Horizontal)
        self.horizontal_slider_scale.setObjectName("horizontal_slider_scale")
        self.horizontal_layout_scale.addWidget(self.horizontal_slider_scale)
        self.spin_box_scale = QtWidgets.QSpinBox(form)
        self.spin_box_scale.setSuffix("%")
        self.spin_box_scale.setMinimum(25)
        self.spin_box_scale.setMaximum(500)
        self.spin_box_scale.setSingleStep(5)
        self.spin_box_scale.setProperty("value", 100)
        self.spin_box_scale.setObjectName("spin_box_scale")
        self.horizontal_layout_scale.addWidget(self.spin_box_scale)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.SpanningRole, self.horizontal_layout_scale)

        self.retranslateUi(form)
        QtCore.QMetaObject.connectSlotsByName(form)

    def retranslateUi(self, form):
        pass
