[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[project]
name = "blivechat-login"
dynamic = ["version"]
description = "blivechat登录B站账号插件"
requires-python = ">=3.12"
authors = [{name = "xfgryujk", email = "xfgryujk@126.com"}]
license = {file = "LICENSE"}
classifiers = ["Private :: Do Not Upload"]
dependencies = [
    "aiohttp==3.13.4",
    "blcsdk",
    "pywebview==6.1",
    "yarl==1.17.2",
]

[dependency-groups]
dev = [
    "pyinstaller~=5.13.2",
    "setuptools~=75.1.0",
]

[tool.pdm]
version = {source = "file", path = "plugin.json", pattern = '"version": "([^"]+)"'}
distribution = false

[tool.uv.sources]
blcsdk = {path = "../../blcsdk/", editable = true}
